import {fonts,bulletStyles,blockIcons,checkResume,presets,supportsPhoto} from './model.mjs';
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const iconSymbols={none:'',briefcase:'▣',code:'⌘',book:'▤',star:'★',award:'✦',heart:'♡',globe:'◎'};
export function field(label,path,value,textarea=false){return `<label class="field"><span>${esc(label)}</span>${textarea?`<textarea rows="3" data-path="${esc(path)}">${esc(value)}</textarea>`:`<input type="text" data-path="${esc(path)}" value="${esc(value)}">`}</label>`;}
export function select(label,path,value,options){return `<label class="field"><span>${esc(label)}</span><select aria-label="${esc(label)}" data-path="${esc(path)}">${options.map(([v,l])=>`<option value="${esc(v)}" ${value===v?'selected':''}>${esc(l)}</option>`).join('')}</select></label>`;}
function color(label,path,value,fallback,reset=false){return `<label class="color-field"><span>${label}</span><input type="color" data-path="${path}" value="${value||fallback}" aria-label="${label}">${reset?`<button class="text-button" type="button" data-reset="${path}">${value?'Reset':'Inherited'}</button>`:`<small>${value}</small>`}</label>`;}
function range(label,key,value,min,max,step,suffix){return `<label class="range-field"><span>${label}<output id="output-${key}">${value}${suffix}</output></span><input type="range" min="${min}" max="${max}" step="${step}" value="${value}" data-path="design.${key}" data-suffix="${suffix}"></label>`;}
export function contentPanel(state,selectedSection,selectedBlock){
 const section=state.sections.find(s=>s.id===selectedSection),block=section?.blocks.find(b=>b.id===selectedBlock);
 const si=state.sections.indexOf(section),bi=section?.blocks.indexOf(block),path=`sections.${si}.blocks.${bi}`;
 return `<div class="panel-intro"><div><h2>Your resume, building blocks</h2><p>Click text on the page to edit it directly.</p></div><span class="subtle-icon">✎</span></div>
 <div class="canvas-tip"><span>↖</span><div><strong>Make your changes right on the page.</strong><p>Drag a handle to move a section or block.</p></div></div>
 <div class="sections"><button class="personal-row ${selectedSection==='personal'?'selected':''}" data-select-section="personal"><span>♙</span> Personal details <span>↗</span></button>
 ${state.sections.map(s=>`<div class="section-card ${selectedSection===s.id?'expanded':''}" data-section="${esc(s.id)}"><div class="section-row"><button class="drag-handle" draggable="true" data-drag-section="${esc(s.id)}" aria-label="Drag section ${esc(s.title)}">⠿</button><button class="section-head" data-select-section="${esc(s.id)}"><span class="section-title">${esc(s.title)||'Untitled section'}<small>${s.blocks.length} ${s.blocks.length===1?'block':'blocks'}</small></span><span class="column-badge">${s.column==='main'?'Main':'Side'}</span><span class="chevron">${selectedSection===s.id?'−':'+'}</span></button></div>${selectedSection===s.id?`<div class="block-list">${s.blocks.map(b=>`<div class="block-list-row ${b.id===selectedBlock?'active':''}" data-block="${esc(b.id)}"><button class="drag-handle" draggable="true" data-drag-block="${esc(b.id)}" aria-label="Drag block ${esc(b.title||s.title)}">⠿</button><button data-select-block="${esc(b.id)}"><span>${iconSymbols[b.icon]||'▱'}</span><span>${esc(b.title||b.paragraph.slice(0,28)||'List block')}</span><span>›</span></button></div>`).join('')}<button class="text-button block-list-add" data-add-block="${esc(s.id)}">＋ Add a block</button></div>`:''}</div>`).join('')}</div>
 <button class="add-section" id="add-section">＋ <span>Add a section</span></button>
 ${selectedSection==='personal'?`<div class="inspector"><h3>PERSONAL DETAILS</h3>${field('Full name','name',state.name)}${field('Job title','role',state.role)}${field('Email address','email',state.email)}${field('Phone number','phone',state.phone)}${field('Location','location',state.location)}${field('Website or portfolio','website',state.website)}<div class="photo-editor"><div class="photo-editor-heading"><strong>Portrait photo</strong><small>Editorial and Modern layouts</small></div><div class="photo-editor-row">${state.photo?`<img src="${esc(state.photo)}" alt="Current resume photo">`:`<div class="photo-editor-placeholder" aria-hidden="true">♙</div>`}<div><button class="button outline" id="choose-photo" type="button">${state.photo?'Replace photo':'Add photo'}</button>${state.photo?`<button class="text-button danger" id="remove-photo" type="button">Remove photo</button>`:''}</div></div><p>JPG, PNG or WebP. Resized and saved in this browser.</p><div class="two-fields">${select('Photo shape','design.photoShape',state.design.photoShape,[['auto','Match layout'],['circle','Circle'],['rounded','Rounded'],['square','Square']])}${select('Photo framing','design.photoPosition',state.design.photoPosition,[['center','Center'],['top','Top'],['bottom','Bottom']])}</div>${range('Photo size','photoSize',state.design.photoSize,72,128,2,'px')}</div></div>`:section?`<div class="inspector"><div class="inspector-heading"><h3>${block?'BLOCK SETTINGS':'SECTION SETTINGS'}</h3>${block?`<button class="text-button" data-select-section="${esc(section.id)}">Section settings ↗</button>`:''}</div>
 ${block?`<div class="selected-block-name">${esc(block.title||section.title)}<span>Changes apply to this block</span></div><div class="block-actions"><button class="mini-button" data-block-up="${esc(block.id)}" ${bi===0?'disabled':''} aria-label="Move block up">↑</button><button class="mini-button" data-block-down="${esc(block.id)}" ${bi===section.blocks.length-1?'disabled':''} aria-label="Move block down">↓</button><button class="mini-button" data-duplicate-block="${esc(block.id)}">Duplicate</button><button class="mini-button danger" data-delete-block="${esc(block.id)}">Delete</button></div>
 ${field('Title',`${path}.title`,block.title)}${field('Subtitle',`${path}.subtitle`,block.subtitle)}<div class="two-fields">${field('Dates',`${path}.date`,block.date)}${field('Location',`${path}.location`,block.location)}</div>${field('Paragraphs',`${path}.paragraph`,block.paragraph,true)}${field('Bullet points · one per line',`${path}.bullets`,block.bullets.join('\n'),true)}
 <div class="two-fields">${select('Block icon',`${path}.icon`,block.icon,blockIcons)}${select('Bullet style',`${path}.style.bulletStyle`,block.style.bulletStyle,[['inherit','Use resume style'],...bulletStyles])}</div>
 <div class="two-fields">${select('Block font',`${path}.style.font`,block.style.font,[['inherit','Use resume font'],...fonts])}${select('Block frame',`${path}.style.border`,block.style.border,[['none','None'],['line','Accent line'],['card','Rounded card']])}</div>
 <div class="block-colors">${color('Title color',`${path}.style.titleColor`,block.style.titleColor,state.design.accent,true)}${color('Subtitle color',`${path}.style.subtitleColor`,block.style.subtitleColor,state.design.subtitleColor,true)}${color('Text color',`${path}.style.textColor`,block.style.textColor,state.design.textColor,true)}${color('Block background',`${path}.style.background`,block.style.background,'#ffffff',true)}</div>
 ${select('Move to section',`move-block:${block.id}`,section.id,state.sections.map(s=>[s.id,`${s.title} (${s.column})`]))}
 <button class="button outline full" data-save-preset="${esc(block.id)}">✦ Save as reusable block</button><p class="field-hint">A saved block keeps its content and styling. Insert independent copies from the block library.</p>`:
 `${field('Section heading',`sections.${si}.title`,section.title)}${select('Column',`sections.${si}.column`,section.column,[['main','Main column'],['side','Side column']])}<div class="block-actions"><button class="mini-button" data-section-up="${esc(section.id)}" ${si===0?'disabled':''}>↑ Move up</button><button class="mini-button" data-section-down="${esc(section.id)}" ${si===state.sections.length-1?'disabled':''}>↓ Move down</button><button class="mini-button danger" data-delete-section="${esc(section.id)}">Delete section</button></div>`}</div>`:''}
 <div class="editor-bottom"><button class="text-button" id="import">↑ Import backup</button><span>JSON · yours to keep</span></div>`;
}
export function designPanel(state){const d=state.design;
 return `<div class="panel-intro"><div><h2>A style that feels like you</h2><p>Set the defaults. Fine-tune individual blocks.</p></div><span class="subtle-icon">◈</span></div><div class="design-content"><h3>START WITH A LAYOUT</h3><div class="template-grid">${['editorial','classic','modern'].map(t=>`<button class="template ${d.template===t?'selected':''}" data-template="${t}"><span class="template-preview ${t}"><i></i><b></b><em></em><em></em><em></em></span><span>${t[0].toUpperCase()+t.slice(1)}</span>${d.template===t?'<span class="template-check">✓</span>':''}</button>`).join('')}</div><p class="template-photo-note">Portrait photos appear in Editorial and Modern. Classic keeps the header text-only.</p><h3>COLOR PALETTE</h3><div class="swatches">${['#205c52','#263d66','#990000','#705174','#303438','#ab7831'].map(c=>`<button class="swatch ${d.accent===c?'selected':''}" style="--swatch:${c}" data-color="${c}" aria-label="Use ${c}">${d.accent===c?'✓':''}</button>`).join('')}</div>
 ${color('Heading color','design.accent',d.accent)}${color('Subtitle color','design.subtitleColor',d.subtitleColor)}${color('Body text color','design.textColor',d.textColor)}
 <button class="button outline full reference-style" id="reference-style"><span class="reference-sample">Aa</span><span>Engineering style<small>Burgundy headings · orange subtitles · rules</small></span></button>
 <div class="two-fields">${select('Typography','design.font',d.font,fonts)}${select('Page size','design.paper',d.paper,[['a4','A4'],['letter','US Letter']])}</div><div class="two-fields">${select('Bullet style','design.bulletStyle',d.bulletStyle,bulletStyles)}${select('Section headings','design.headingStyle',d.headingStyle,[['plain','Spaced capitals'],['line','Underlined'],['band','Color band']])}</div>
 <h3>LAYOUT & SPACING</h3><div class="segmented">${[1,2].map(n=>`<button data-columns="${n}" class="${d.columns===n?'active':''}">${n===1?'▤ One column':'▥ Two columns'}</button>`).join('')}</div>
 ${range('Column balance','ratio',d.ratio,50,75,1,'%')}${range('Page margins','margin',d.margin,20,64,2,'px')}${range('Section spacing','spacing',d.spacing,8,36,2,'px')}${range('Font size','size',d.size,8,13,.5,'pt')}${range('Line height','lineHeight',d.lineHeight,1.2,1.9,.05,'×')}
 <h3>FINISHING TOUCHES</h3><div class="two-fields">${select('Background','design.background',d.background,[['clean','Pure white'],['tinted','Warm paper'],['sidebar','Soft sidebar']])}${select('Metadata icons','design.icons',d.icons,[['minimal','Minimal'],['classic','Classic'],['none','No icons']])}</div><div class="tip-box">✦ <span>Select a block on the page to give it its own font, colors, frame, and bullet style.</span></div></div>`;
}
export function checkPanel(state,job){const result=checkResume(state,job),matched=result.keywords.filter(k=>k.found).length;
 return `<div class="panel-intro"><div><h2>A second pair of eyes</h2><p>Small improvements. A stronger story.</p></div></div><div class="check-content"><div class="score-card"><div class="score-ring" style="--score:${result.score}%"><strong>${result.score}<small>/ 100</small></strong></div><div><h2>${result.score>=85?'Looking sharp.':result.score>=60?'A solid foundation.':'Let’s build your story.'}</h2><p>${result.checks.filter(c=>c.pass).length} of ${result.checks.length} checks passed</p></div></div><p class="score-disclaimer">An explained writing and formatting checklist, not an employer’s ATS score or a hiring prediction. All analysis happens on your device.</p><div class="check-list">${result.checks.map(c=>`<div class="check-item"><span class="check-icon ${c.pass?'passed':''}">${c.pass?'✓':'!'}</span><div><strong>${c.label}</strong><p>${c.detail}</p></div><small>${c.pass?c.weight:0}/${c.weight}</small></div>`).join('')}</div><h3>TAILOR TO A JOB</h3><label class="field"><span>Paste a job description</span><textarea rows="5" id="job-description" placeholder="What is your next team looking for?">${esc(job)}</textarea></label><button class="button primary full" id="match-job">Check keyword match</button>${result.keywords.length?`<div class="keyword-result"><strong>${matched} of ${result.keywords.length} keywords found</strong><p>Simple word matching, not a relevance score. Add terms only when they truthfully reflect your experience.</p><div class="keywords">${result.keywords.map(k=>`<span class="${k.found?'found':''}">${k.found?'✓ ':''}${esc(k.word)}</span>`).join('')}</div></div>`:''}</div>`;
}
function editable(tag,path,text,label,classes='',multiline=false){return `<${tag} class="editable ${classes} ${text?'':'is-empty'}" contenteditable="plaintext-only" role="textbox" aria-label="${esc(label)}" aria-multiline="${multiline}" data-edit="${path}" data-placeholder="${esc(label)}" spellcheck="true">${esc(text)}</${tag}>`;}
function blockHtml(block,si,bi,selected){
 const p=`sections.${si}.blocks.${bi}`,s=block.style;
 const vars=[['--block-title',s.titleColor],['--block-subtitle',s.subtitleColor],['--block-text',s.textColor],['--block-bg',s.background]].filter(([,v])=>v).map(([k,v])=>`${k}:${v}`).join(';');
 return `<div class="resume-block ${selected===block.id?'selected':''} font-${s.font} frame-${s.border} bullets-${s.bulletStyle}" data-block="${esc(block.id)}" style="${vars}">
 <div class="block-toolbar canvas-control" contenteditable="false"><button draggable="true" data-drag-block="${esc(block.id)}" aria-label="Drag block ${esc(block.title||'untitled')}">⠿</button><span>BLOCK</span><button data-block-up="${esc(block.id)}" aria-label="Move block up">↑</button><button data-block-down="${esc(block.id)}" aria-label="Move block down">↓</button><button data-duplicate-block="${esc(block.id)}" aria-label="Duplicate block">⧉</button><button data-delete-block="${esc(block.id)}" aria-label="Delete block">×</button></div>
 <div class="block-title-row">${block.icon!=='none'?`<span class="block-icon" aria-hidden="true">${iconSymbols[block.icon]}</span>`:''}${editable('h3',`${p}.title`,block.title,'Block title','block-title')}</div>
 ${editable('div',`${p}.subtitle`,block.subtitle,'Block subtitle','entry-subtitle')}
 <div class="block-metadata"><span class="metadata-part ${block.date?'':'empty-part'}"><span class="metadata-icon" aria-hidden="true">▦</span>${editable('span',`${p}.date`,block.date,'Dates')}</span><span class="metadata-part ${block.location?'':'empty-part'}"><span class="metadata-icon" aria-hidden="true">⌖</span>${editable('span',`${p}.location`,block.location,'Location')}</span></div>
 ${editable('p',`${p}.paragraph`,block.paragraph,'Write a paragraph…','block-paragraph',true)}
 <ul class="block-bullets">${block.bullets.map((b,i)=>`<li>${editable('span',`${p}.bullets.${i}`,b,`Bullet ${i+1}`,'bullet-text')}<button class="remove-bullet canvas-control" data-remove-bullet="${esc(block.id)}" data-bullet-index="${i}" aria-label="Remove bullet ${i+1}">×</button></li>`).join('')}</ul>
 <div class="block-inline-actions canvas-control"><button data-add-bullet="${esc(block.id)}">＋ Bullet</button><button data-add-paragraph="${esc(block.id)}">＋ Paragraph</button><button data-save-preset="${esc(block.id)}">✦ Save block</button></div></div>`;
}
function sectionHtml(section,si,selectedSection,selectedBlock){return `<section class="resume-section ${selectedSection===section.id?'section-selected':''}" data-section="${esc(section.id)}"><div class="section-heading-row">${editable('h2',`sections.${si}.title`,section.title,'Section heading')}<button class="section-canvas-handle canvas-control" draggable="true" data-drag-section="${esc(section.id)}" aria-label="Drag section ${esc(section.title)}">⠿</button></div><div class="section-blocks">${section.blocks.map((b,bi)=>blockHtml(b,si,bi,selectedBlock)).join('')}<button class="canvas-add-block canvas-control" data-add-block="${esc(section.id)}">＋ Add block</button></div></section>`;}
export function resumeHtml(state,selectedSection,selectedBlock){const d=state.design;
 const symbols=d.icons==='classic'?['✉','☎','⌖','↗']:['@','⌕','⌖','↗'];
 const hasPhoto=!!state.photo&&supportsPhoto(d.template);
 const portrait=hasPhoto?`<div class="resume-photo-wrap"><img class="resume-photo" src="${esc(state.photo)}" alt="Portrait of ${esc(state.name)}"><button class="photo-change canvas-control" data-upload-photo aria-label="Replace photo">✎</button></div>`:d.template==='modern'?`<div class="resume-monogram">${esc(state.name.split(/\s+/).filter(Boolean).map(n=>n[0]).slice(0,2).join(''))}<span>●</span></div><button class="photo-empty-trigger canvas-control" data-upload-photo aria-label="Add photo">＋</button>`:'';
 const column=key=>`<${key==='side'?'aside':'div'} class="${key}-column column-drop" data-column="${key}">${state.sections.map((s,i)=>({s,i})).filter(({s})=>d.columns===1||s.column===key).map(({s,i})=>sectionHtml(s,i,selectedSection,selectedBlock)).join('')}<button class="column-add canvas-control" data-add-section-column="${key}">＋ Add section${d.columns===2?` to ${key} column`:''}</button></${key==='side'?'aside':'div'}>`;
 return `<header class="resume-header ${selectedSection==='personal'?'section-selected':''} ${hasPhoto?'has-photo':''} photo-shape-${d.photoShape}" data-personal="true">${portrait}${editable('h1','name',state.name,'Full name')}${editable('p','role',state.role,'Job title','resume-role')}<div class="contact-list">${['email','phone','location','website'].map((key,i)=>`<span class="contact-item ${state[key]?'':'empty-part'}">${d.icons!=='none'?`<b aria-hidden="true">${symbols[i]}</b>`:''}${editable('span',key,state[key],key[0].toUpperCase()+key.slice(1))}</span>`).join('')}</div></header><div class="resume-columns ${d.columns===1?'single':''}">${column('main')}${d.columns===2?column('side'):''}</div>`;
}
export function libraryHtml(library,isSection){return `<div class="preset-grid">${presets.map(p=>`<button type="button" data-insert-preset="${p.key}"><span class="preset-icon">${iconSymbols[p.block.icon]||'≡'}</span><strong>${esc(p.label)}</strong><small>${esc(p.description)}</small><span class="preset-plus">＋</span></button>`).join('')}</div>${!isSection?`<h3>YOUR SAVED BLOCKS</h3>${library.length?`<div class="saved-presets">${library.map(p=>`<div><button type="button" data-insert-saved="${esc(p.id)}"><span>✦</span>${esc(p.name)}</button><button type="button" data-delete-preset="${esc(p.id)}" aria-label="Delete saved block ${esc(p.name)}">×</button></div>`).join('')}</div>`:'<p class="library-empty">Style a block on your resume, then choose “Save block” to reuse it here.</p>'}`:''}`;}
